### ISSUE TITLE
The graph stopped working on most devices

### ISSUE THREAD

**Issue by Inffix** [dextools-io/chart-widget#10]
About a week ago, users began to massively report that the widget was not loading. Moreover, it began to completely block the page, as if it were running in an eternal loop. At the same time, for some users everything works as before. Our tests showed that the error did not depend on the IP address or the device, but sometimes changing the browser or its version helped. Please look into it, thank you!

**Comment by pablojan** [comment]
Dear user, we are not able to reproduce your problem. We need more information about your environment. Thanks

**Comment by miguerram** [comment]
Hello, we have released a new version that includes a fix. While we are not sure if it directly addresses your specific issue, it resolves issues similar in nature to those you described. If you continue to experience difficulties, please do not hesitate to contact us, thank you.

**Comment by Inffix** [comment]
Thanks! The issue has indeed been fixed, now the chart works perfectly for all users 🤝
