### ISSUE TITLE
`chartInUsd` queryParam not working

### ISSUE THREAD

**Issue by dev-wasabi** [dextools-io/chart-widget#12]
Setting `chartInUsd` doesn't change anything. I need to display the charts in the denomination token.

Thanks for the help

**Comment by christophercr** [comment]
@dev-wasabi the issue should be solved now. Could you please double check?

Passing the paran `chartInUsd=false` should effectively show the chart with the pair's reference token.

**Comment by dev-wasabi** [comment]
Hello @christophercr , just checked and verified it works. Thanks for the help!

We just launched a perps product and using DexTools charts here if you want to see: https://perps.wasabi.xyz/

**Comment by christophercr** [comment]
Great! We'll check it out for sure!
