### ISSUE TITLE
Got warning for metamask browser

### ISSUE THREAD

**Issue by NhaPCS** [dextools-io/chart-widget#14]
https://prnt.sc/34Rj3OXgsjd_

I used chart-widget but when open inside metamask and trustwallet, it shows warning message like this.

Because of https://github.com/MetaMask/metamask-mobile/blob/23dc52bda442fb3782fdaf1e29f83e81a86249c0/app/components/Views/BrowserTab/index.js#L875-L904

How to avoid showing that alert for my website?

**Comment by christophercr** [comment]
Thanks for your report @NhaPCS . Although I'm afraid the screenshot you send is no longer available. Could you please paste the screenshot directly here in a new comment?

Apart from that, could you tell a bit more about the environment where you have this issue? Device, OS version, metamask app version, etc...

**Comment by christophercr** [comment]
Closing due to innactivity
