### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by liu798675179** [dextools-io/chart-widget#3]
Refused to display 'https://www.dextools.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by msguneyy** [comment]
with react project, gettig 403 error. 
![image](https://github.com/dextools-io/chart-widget/assets/45722886/974a49d4-0624-4422-b032-41d82caeb15d)

**Comment by msguneyy** [comment]
same issue. how we can use it with react project ?

**Comment by pablojan** [comment]
Have you checked following CSP directive in your web server?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
