### ISSUE TITLE
Firefox Can’t Open This Page

### ISSUE THREAD

**Issue by silverpedak** [dextools-io/chart-widget#5]
How to use this widget? Followed the instruction, but got this error:

Firefox Can’t Open This Page

To protect your security, www.dextools.io will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

I asked chatGPT and got this: 
The error message you're encountering suggests that the website [www.dextools.io](http://www.dextools.io/) has implemented a security feature that prevents their page from being embedded within an iframe on another website. This is known as a Content Security Policy (CSP) setting, and it restricts embedding to only specific domains or disables embedding altogether.

So whats the point of the widget if you cannot embed it to your website ?

Thanks

**Comment by pablojan** [comment]
Is the problem still happening? it was caused by a SSL certificate issue, already fixed last friday.

**Comment by silverpedak** [comment]
> Is the problem still happening? it was caused by a SSL certificate issue, already fixed last friday.

Yes, this is still a problem. I tried Chrome aswell.
The error message in console looks like this:
Refused to display 'https://www.dextools.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by christophercr** [comment]
Hi, I suppose you're testing on localhost?
Could you try using a different domain for your website?
